// <auto-generated />
using System;
using GraphQLApp.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200806161550_InitialCommit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQLApp.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29f26ac5-4b25-4078-909b-954cf7da05bf"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("c0e74e96-fc99-4a77-8359-7e996c77b44c"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d6335160-339a-43ad-9323-85f69f4b2253"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("60b0290d-f932-41ea-8c4e-8bc7d3dd9b0d"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("67906937-12e7-4330-bdac-bf1eea039c26"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("60b0290d-f932-41ea-8c4e-8bc7d3dd9b0d"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphQLApp.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0e74e96-fc99-4a77-8359-7e996c77b44c"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("60b0290d-f932-41ea-8c4e-8bc7d3dd9b0d"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphQLApp.Entities.Account", b =>
                {
                    b.HasOne("GraphQLApp.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
